# Site settings
title: Learning Orbit
header-img: img/home-bg.jpg
email: akshay.elavia@gmail.com
copyright_name: Akshay Elavia
description: "A technical blog documenting topics about cloud, security and DevOps"
baseurl: ""
url: "https://itselavia.github.io"
twitter_username: Munchin_Jughead
github_username:  itselavia
facebook_username:  akshay.elavia
email_username:  akshay.elavia@gmail.com
linkedin_username: akshay-elavia-30969919

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]